### ISSUE TITLE
"TypeError: pino.transport is not a function" in Next.js

### ISSUE THREAD

**Issue by lkostrowski** [baselime/pino-transport#1]
Hey, I'm trying to connect Pino with Baselime transport to Next.js app

I have "TypeError: pino.transport is not a function"

Implementation of the logger 

```typescript
const pino = require("pino");

const t = pino.transport({
  target: "@baselime/pino-transport",
  options: { baselimeApiKey: process.env.NEXT_PUBLIC_BASELIME_KEY as string },
});

export const logger = pino(t);
```

```
Next: 14.0.3
Pino 8.16.1
"@baselime/node-opentelemetry": "^0.2.13",
"@baselime/pino-transport": "^0.1.5",
"@baselime/react-rum": "^0.2.5",
"@opentelemetry/api": "1.6.0",
"@opentelemetry/auto-instrumentations-node": "^0.40.0",
```

**Comment by Ankcorn** [comment]
Hi @lkostrowski 

thanks for raising the issue, can I just confirm pino is installed in this project?

**Comment by lkostrowski** [comment]
Repro I am working on https://github.com/lkostrowski/baselime-test

**Comment by Ankcorn** [comment]
Hey @lkostrowski thanks for reporting this, I am taking a look and trying to get your reproduction working on my machine.

**Comment by Ankcorn** [comment]
One thing to check though, this won't work well when deployed to Vercel if that is your intention. The pino-transports batch but have no idea that the serverless runtime will just exit after responding to the request

https://vercel.com/integrations/baselime This will forward the logs with no code changes.

**Comment by lkostrowski** [comment]
@Ankcorn I see, 

So if I use pino, you recommend to apply standard console.log transport for Vercel, so log drain can pick this up?

>The pino-transports batch but have no idea that the serverless runtime will just exit after responding to the request

This part is tricky I know, if you like to achieve that, there are packages like Sentry that monkey-patches serverless responses to flush logs

**Comment by Ankcorn** [comment]
Yes, Pino without a transport will work on vercel :) 

It's better to write logs via the drain because that is completely asynchronous. 

Interesting do you have an example where the sentry patches the response for next.js?

**Comment by lkostrowski** [comment]
https://github.com/getsentry/sentry-javascript/blob/6f4edf883f639c2da00fb1eb3ac1062fce211439/packages/nextjs/src/common/wrapRouteHandlerWithSentry.ts

**Comment by Ankcorn** [comment]
I think this webpack plugin would resolve your issue https://www.npmjs.com/package/pino-webpack-plugin but I would recommend using the logdrain instead :)

**Comment by lkostrowski** [comment]
> I think this webpack plugin would resolve your issue [npmjs.com/package/pino-webpack-plugin](https://www.npmjs.com/package/pino-webpack-plugin)

Thanks, I will check this out. I think you can mention this in docs too
